version: '3'
services:
  react-app:
    container_name: react-app
    image: react-app
    build: ./
    command: serve -s build
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
